@extends('layouts.app')

@section('title', 'View all Reports')


@section('content')

    <x-handlers.alerts/>
    <section>
        <p class="mb-4">Below are all the Reports generated by the Users. These reports are available for 7 days before
                        they are automatically deleted, please print or download
                        prior to the expiry date. </p>
        <div class="card shadow mb-4">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="assetsTable" class="table table-striped">
                        <thead>
                        <tr>
                            <th class="col-5"><small>Report</small></th>
                            <th class="col-2 col-md-auto"><small>Generated By:</small></th>
                            <th class="col-2 col-md-auto text-center"><small>Date</small></th>
                            <th class="col-2 text-center"><small>Expiry</small></th>
                            <th class="col-1 text-right"><small>Options</small></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th class="col-5"><small>Report</small></th>
                            <th class="col-2 col-md-auto"><small>Generated By:</small></th>
                            <th class="col-2 col-md-auto text-center"><small>Date</small></th>
                            <th class="col-2 text-center"><small>Expiry</small></th>
                            <th class="col-1 text-right"><small>Options</small></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($reports as $report)
                            <tr>
                                <td>
                                    @if(file_exists($report->report))
                                        @if(str_contains( $report->report ,'reports' ))
                                            @php $name = str_replace('storage/reports/' , '' ,$report->report);@endphp
                                        @endif
                                        @if(str_contains( $report->report ,'csv' ))
                                            @php $name = str_replace('storage/csv/' , '' ,$report->report);@endphp
                                        @endif
                                        <a href="{{ asset($report->report)}}" target='_blank'
                                           title="New">{{$name ??$report->report }}</a>
                                    @else
                                        @if(str_contains( $report->report ,'reports' ))
                                            @php $name = str_replace('storage/reports/' , '' ,$report->report);@endphp
                                        @endif
                                        @if(str_contains( $report->report ,'csv' ))
                                            @php $name = str_replace('storage/csv/' , '' ,$report->report);@endphp
                                        @endif
                                        @if(\Carbon\Carbon::now()->floatDiffInMinutes($report->created_at) < 15)
                                            {!! $name .' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>' !!}
                                        @else
                                            <span class='text-coral'> {{substr($report->report,16)}} <i
                                                    class='fas fa-times'></i></span>
                                        @endif
                                    @endif
                                </td>
                                <td>{{ $report->user->name ?? 'N/A' }}</td>
                                <td class="text-center"
                                    data-sort="{{  strtotime($report->created_at) }}">{{ \Carbon\Carbon::parse($report->created_at)->format('d/m/Y H:i:s')}}</td>
                                <td class="text-center"
                                    data-sort="{{ strtotime($report->created_at)+(60*60*24*7)}}">{{ \Carbon\Carbon::parse($report->created_at)->addDays(7)->format('d/m/Y H:i:s') }}</td>
                                <td class="text-right">...</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <x-paginate :model="$reports"/>
                </div>
            </div>
        </div>

        <div class="card shadow mb-3">
            <div class="card-body">
                <h4>Help with Assets</h4>
                <p>This area can be minimised and will contain a little help on the page that the user is currently
                   on.</p>
            </div>
        </div>

    </section>
@endsection


